config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  resources :statuses do
  end
end

app/models/application_record.rb
# frozen_string_literal: true

# Application Record
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
# frozen_string_literal: true

# Status model
class Status < ApplicationRecord
  has_many :tasks, dependent: :destroy
  accepts_nested_attributes_for :tasks
  validates :date, presence: true

  def total_hours
    tasks.sum(:hours)
  end
end

app/models/task.rb
# frozen_string_literal: true

# Task model
class Task < ApplicationRecord
  belongs_to :status
  validates :task_name, presence: true, length: { in: 5..100 }
  validates :pr_links, presence: true, length: { in: 10..100 }, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
  validates :hours, presence: true, numericality: { in: 0..24 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

# Application Controller
class ApplicationController < ActionController::Base
  helper_method :flash_messages
  def flash_messages(name)
    name == 'notice' ? 'success' : 'danger'
  end
end

app/controllers/pages_controller.rb
# frozen_string_literal: true

# Pages Controller
class PagesController < ApplicationController
  def home; end
end

app/controllers/status_controller.rb
# frozen_string_literal: true

# Status Controller
class StatusController < ApplicationController
  before_action :set_status, only: %i[show edit update destroy]

  def index
    @statuses = Status.all
  end

  def show; end

  def new
    @status = Status.new
  end

  def create
    @status = Status.new(status_params)

    if @status.save
      redirect_to @status
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @status.update(status_params)
      redirect_to @status
    else
      render 'edit'
    end
  end

  def destroy
    @status.destroy
    redirect_to status_index_path
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:date, :tasks, :pr_links, :hours)
  end
end

app/controllers/statuses_controller.rb
# frozen_string_literal: true

# Statuses Controller
class StatusesController < ApplicationController
  before_action :set_status, only: %i[show edit update destroy]

  def index
    @statuses = Status.paginate(page: params[:page], per_page: 3)
  end

  def show
    @tasks = @status.tasks
  end

  def new
    @status = Status.new
    @tasks = @status.tasks.build
  end

  def create
    @status = Status.new(status_params)
    if @status.save
      StatusMailer.with(status: @status).new_status_email.deliver_later
      flash[:notice] = 'Status update was created & Mail has sent successfully'
      redirect_to @status
    else
      render 'new'
    end
  end

  def edit; end

  def update
    if @status.update(status_params)
      flash[:notice] = 'Status update was updated successfully.'
      redirect_to @status
    else
      render 'edit'
    end
  end

  def destroy
    @status.destroy
    flash[:alert] = 'Status was successfully deleted'
    redirect_to root_path
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:date, tasks_attributes: %i[id task_name pr_links hours _destroy])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

# Application Helper module
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
    <small>Copyright &copy; Daily status</small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
  <% flash.each do |name, msg| %>
    <div class="alert alert-<%= flash_messages(name) %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-dark">
  <div class="container-fluid">
    <h1>
      <%= link_to "DAILY STATUS", root_path, class: "navbar-brand", id: "logo" %>
    </h1>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Daily status</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navigation' %>
    <div id="page-content">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" id="home-container">
  <div class="jumbotron bg-light p-5 rounded-lg m-3">
    <h1 class="display-4">Hello, Employees!</h1>
    <p class="lead">Welcome to Daily status update Application.</p>
    <hr class="my-4">
    <p>Click below button for create the new status update</p>
    <%= link_to "Create", new_status_path, class: "btn btn-outline-primary btn-lg mb-3" %>
    <br>
    <p>Click below button for the History of status update</p>
    <%= link_to "Status History", statuses_path, class: "btn btn-outline-info btn-lg" %>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
    <ul>
      <% obj.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/status/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
  <%= form_with(model: @statuses, class: "shadow p-3 mb-3 bg-white rounded", local: true) do |f| %>
    <div class="row mb-3">
      <%= f.label :date, class: "col-sm-2 col-form-label text-dark" %>
      <div class="col-sm-10"> 
        <%= f.text_field :date, class: "form-control shadow rounded", placeholder: "Date of the day" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :tasks, class: "col-sm-2 col-form-label text-dark" %>
      <div class="col-sm-10"> 
        <%= f.text_area :tasks, rows: 3, class: "form-control shadow rounded", placeholder: "Task of the day" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :pr_links, class: "col-sm-2 col-form-label text-dark" %>
      <div class="col-sm-10"> 
        <%= f.text_area :pr_links, rows: 3, class: "form-control shadow rounded", placeholder: "PR of the GitHub" %>
      </div>
    </div>

    <div class="row mb-3">
      <%= f.label :hours, class: "col-sm-2 col-form-label text-dark" %>
      <div class="col-sm-10"> 
        <%= f.text_field :hours, class: "form-control shadow rounded", placeholder: "Hours you spent" %>
      </div>
    </div>

    <div class="d-flex justify-content-center">
      <%= f.submit class: "btn btn-outline-dark btn-lg" %>
    </div>
   
  <% end %>
  </div>
</div>

app/views/status/edit.html.erb
<h1 class="text-center mt-4">Edit status</h1>
<%= render "form" %>

app/views/status/index.html.erb
<h1 class="text-center mt-4">Status History</h1>

<table style="width:50%" class="center">
  <tr>
    <th>Date</th>
    <th>Tasks</th> 
    <th>PR Links</th>
    <th>Hours</th>
  </tr>
    <% @statuses.each do |status| %>
    <tr>
      <td><%= status.date %></td>
      <td><%= status.tasks %></td>
      <td><%= status.pr_links %></td> 
      <td><%= status.hours %></td>
    </tr>
    <% end %>
</table>

app/views/status/new.html.erb
<h1 class="text-center mt-4">New Status Update</h1>
<%= render "form", status: @status %>

app/views/status/show.html.erb
<h1 class="text-center mt-4">Preview Email</h1>

<h2 class="text-center mt-4">Subject Line: Status update for <%= @status.date %> </h2>
<h3 class="text-center mt-4">Here is the Status update</h3>

<table style="width:50%" class="center">
  <tr>
    <th>Date</th>
    <th>Tasks</th> 
    <th>PR Links</th>
    <th>Hours</th>
  </tr>
  <tr>
    <td><%= @status.date %></td>
    <td><%= @status.tasks %></td>
    <td><%= @status.pr_links %></td> 
    <td><%= @status.hours %></td>
  </tr>
</table>

app/views/statuses/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-10">
      <%= render 'shared/errors', obj: @status %>
      <%= form_for(@status) do |f| %>
        <div class="row mb-3 fw-bold">
          <%= f.label :date %>
          <div>
            <%= f.date_field :date, min:"2001-01-01", max:"#{Date.today.to_s}" %>
          </div>
        </div>
         
        <div>
          <%= f.fields_for :tasks do |t| %>
            <%= render "task_fields", f: t %>
          <% end %>
          <div>
            <br>
            <%= link_to_add_association f, :tasks do %>
              <button class="btn btn-outline-success" type="submit">Add task</button>
            <% end %>

            <button type="button" class="btn btn-outline-secondary ms-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
              Preview Mail
            </button>
          </div>
        </div>
         
        <div class="d-flex justify-content-center">
          <%= f.submit class: "btn btn-outline-success mb-3"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="staticBackdropLabel">Training status</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>

      <div class="modal-body">
        <p>Hi Nishant sir, <br>
          <p class="ml-5">Please find the status for Today.</p>
            <p>
              <table class="table table-light table-hover text-center">
                <tr class="table-dark text-center">
                  <th>Tasks</th>
                  <th>PR Links</th>
                  <th>Hours</th>
                </tr>
  
                <% @status.tasks.each do |task| %>
                  <tr class="text-center">
                    <td><input type="text" class="form-control" id="text_name" disabled></td>
                    <td><input type="text" class="form-control" id="text_pr" disabled></td>
                    <td><input type="text" class="form-control" id="text_hours" disabled></td>
                  </tr>
                <% end %>
              </table>
            </p>
        </p>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Done!</button>
      </div>
    </div>
  </div>
</div>

app/views/statuses/_task_fields.html.erb
<div class="col-15">
  <div class= "">
    <div class="nested-fields shadow p-3 mb-3 bg-light rounded">
      <div class="row mb-3 fw-bold">
        <%= f.label :task_name, class: "col-sm-2 col-form-label text-dark" %>
        <div class="col-sm-10">
          <%= f.text_field :task_name, class: "form-control shadow rounded", placeholder: "Name of the task", id: "task_name" %>
        </div>
      </div>
    
      <div class="row mb-3 fw-bold">
        <%= f.label :pr_links, class: "col-sm-2 col-form-label text-dark" %>
        <div class="col-sm-10">
          <%= f.url_field :pr_links, class: "form-control shadow rounded", placeholder: "Github PR of task", id: "pr_link" %>
        </div>
      </div>
  
      <div class="row mb-3 fw-bold">
        <%= f.label :hours, class: "col-sm-2 col-form-label text-dark" %>
        <div class="col-sm-10">
          <%= f.number_field :hours, in:(0..24),step: 0.5, class: "form-control shadow rounded", placeholder: "Hours of the task", id: "time" %>
        </div>
      </div>
    
      <div class="d-flex justify-content-center">
        <%= link_to_remove_association "Delete", f, class:"btn btn-outline-danger ms-3" %>
      </div>
    </div>
  </div>
</div>

app/views/statuses/edit.html.erb
<h1 class="text-center mt-4">Edit status</h1>
<%= render "form" %>

app/views/statuses/index.html.erb
<h1 class="text-center mt-4">Status History</h1>

<h3 class="text-center mt-4">Total statuses: <%= @statuses.count %></h3>

<div class="flickr_pagination mt-3 mb-4">
  <%= will_paginate @statuses, :container => false %>
</div>

<div class="table-responsive">
  <table style="width:70%" class="table table-light table-hover center text-center">
    <tr class="table-dark text-center">
      <th>Date</th>
      <th>Action</th>
    </tr>

    <% @statuses.each do |status| %>
      <tr>
        <td><%= status.date.strftime('%d/%m/%Y') %></td>
        <td><%= link_to 'View', status_path(status), class:"btn btn-outline-primary" %></td>
      </tr>
    <% end %>
  </table>
</div>


<div class="flickr_pagination mb-4">
  <%= will_paginate @statuses, :container => false %>
</div>

<div class="d-flex justify-content-center">
  <%= link_to 'Home page', root_path, class: "btn btn-outline-dark mb-3" %>
</div>

app/views/statuses/new.html.erb
<h1 class="text-center mt-4">New Status Update</h1>
<%= render "form" %>

app/views/statuses/show.html.erb
<h2 class="text-center mt-4">Status update for <%= @status.date.strftime('%d/%m/%Y') %></h2>

<h3 class="text-center mt-4">Total Tasks: <%= @tasks.count %></h3>

<div class="table-responsive">
  <table style="width:70%" class="table table-light table-hover center">
    <tr class="table-dark text-center">
      <th>Tasks</th>
      <th>PR Links</th>
      <th>Hours</th>
    </tr>
    
    <% @tasks.each do |task| %>
      <tr class="text-center">
        <td><%= task.task_name %></td>
        <td><%= link_to task.pr_links, task.pr_links, target: '_blank' %></td>
        <td><%= task.hours %></td>
      </tr>
    <% end %>
  </table>

  <h3 class="text-center mt-4">Total Hours: <%= pluralize(@status.total_hours, "hour") %></h3>
  <div class="d-flex justify-content-center">
    <%= link_to 'EDIT', edit_status_path(@status), class:"btn btn-outline-primary mb-3" %>
    <%= link_to 'DELETE', status_path(@status), method: :delete, data: { confirm: "Are you sure?" }, class:"btn btn-outline-danger ms-2 mb-3" %>
  </div>
</div> 

<div class="d-flex justify-content-center">
  <%= link_to "Status History", statuses_path, class: "btn btn-outline-dark mb-3 mt-3"%>
</div>